In [2]:
import pandas as pd
import numpy as np

In [3]:
d = pd.read_csv(r"C:\Users\ponra\Downloads\archive (3)\Bank_Personal_Loan_Modelling.csv")

In [4]:
d.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [5]:
d.drop('ID',axis=1,inplace=True)

In [6]:
d['CCAvg'] = d['CCAvg'].astype('int64')

In [14]:
d.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [15]:
d.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [9]:
d.columns=['Age', 'Experience', 'Income', 'ZIP Code', 'Family', 'CCAvg',
       'Education', 'Mortgage', 'Securities Account',
       'CD Account', 'Online', 'CreditCard','Personal Loan']

In [10]:
d = np.array(d)
m,n = d.shape

In [11]:
n

13

In [12]:
dd = d.T
y = dd[-1]
x = dd[0:n]

In [13]:
x.shape

(13, 5000)

In [71]:
def generate():
    w1 = 0.1*np.random.randn(8,13)
    b1 = 0.1*np.random.randn(8,1)
    w2 = 0.1*np.random.randn(2,8)
    b2 = 0.1*np.random.randn(2,1)
    return w1,b1,w2,b2

def sigmoid(z):
    return 1/(1+np.exp(-z))

def forward(w1,b1,w2,b2,x):
    z1 = w1.dot(x)+b1
    a1 = sigmoid(z1)
    z2 = w2.dot(a1)+b2
    a2 = sigmoid(z2)
    return z1,a1,z2,a2


def der(z):
    return sigmoid(z)*(1-sigmoid(z))

def back(z1,a1,z2,a2,w1,w2,x,y):
    print(a2)
    er = a2 - y
    #error in outer layer
    delt = er * der(z2)
    dw2 = (1 / m) *delt.dot(a1.T)
    db2 = (1 / m )* np.sum(er)
    #error in hidden layer
    delt_hid = w2.T.dot(delt) * der(z1)
    dw1 = (1 / m )* delt_hid.dot(x.T)
    db1 = (1 / m )* np.sum(delt_hid)
    
    return dw1,db1,dw2,db2

def update(w1,b1,w2,b2,dw1,db1,dw2,db2,a):
    w1 = w1 + a*dw1
    b1 = b1 + a*db1
    w2 = w2 + a*dw2
    b2 = b2 + a*db2
    return w1,b1,w2,b2

In [74]:
def get_predictions(a2):
    return np.argmax(a2, 0)

def get_accuracy(predictions, y):
    print(predictions, y)
    return np.sum(predictions == y) / y.size

def gradient(x,y,a,it):
    w1,b1,w2,b2 = generate()
    for i in range(it):
        z1,a1,z2,a2 = forward(w1,b1,w2,b2,x)
        dw1,db1,dw2,db2 = back(z1,a1,z2,a2,w1,w2,x,y)
        w1,b1,w2,b2 = update(w1,b1,w2,b2,dw1,db1,dw2,db2,a)
        if i % 5 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(a2)
            print(get_accuracy(predictions, y))
    return w1, b1, w2, b2

In [75]:
p=np.zeros((5000,1))
p = p.T
w1, b1, w2, b2 = gradient(x, y, 0.1,100)

C:\Users\ponra\AppData\Local\Temp\ipykernel_35476\2160665534.py:9: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-z))


[[0.43901088 0.43901088 0.43901088 ... 0.43901088 0.43901088 0.43901088]
 [0.5605953  0.5605953  0.5605953  ... 0.5605953  0.5605953  0.5605953 ]]
Iteration:  0
[1 1 1 ... 1 1 1] [0 0 0 ... 0 0 1]
0.294
[[0.45359393 0.45359393 0.45359393 ... 0.45359393 0.45359393 0.45359393]
 [0.5787329  0.5787329  0.5787329  ... 0.5787329  0.5787329  0.5787329 ]]
[[0.46955024 0.46955024 0.46955024 ... 0.46955024 0.46955024 0.46955024]
 [0.59789833 0.59789833 0.59789833 ... 0.59789833 0.59789833 0.59789833]]
[[0.48696728 0.48696728 0.48696728 ... 0.48696728 0.48696728 0.48696728]
 [0.61802922 0.61802922 0.61802922 ... 0.61802922 0.61802922 0.61802922]]
[[0.50591509 0.50591509 0.50591509 ... 0.50591509 0.50591509 0.50591509]
 [0.6390257  0.6390257  0.6390257  ... 0.6390257  0.6390257  0.6390257 ]]
[[0.52643564 0.52643564 0.52643564 ... 0.52643564 0.52643564 0.52643564]
 [0.66074722 0.66074722 0.66074722 ... 0.66074722 0.66074722 0.66074722]]
Iteration:  5
[1 1 1 ... 1 1 1] [0 0 0 ... 0 0 1]
0.294
[[0.54